### Importing my Custom Library

In [1]:
from vf1 import F1VS, F1Map
import numpy as np

#### Creating F1 Vector Spaces

In [2]:
v1 = F1VS([1,2,3])
v2 = F1VS([4, 5])

In [3]:
print(f"v1 = {v1}, v2 = {v2}")

v1 = {0, 1, 2, 3}, v2 = {0, 4, 5}


#### Type of Vector Spaces

In [4]:
print("Type of v1 is :",type(v1))
print("Type of v2 is :",type(v2))

Type of v1 is : <class 'vf1.F1VS'>
Type of v2 is : <class 'vf1.F1VS'>


#### Computing F1 Sub Spaces

In [5]:
subv1 = v1.subset([2])
print("Sub Space of v1 = ",subv1)

Sub Space of v1 =  {0, 2}


#### Computing Direct Sum of F1 Vector Spaces

In [6]:
v1_dsum_v2 = v1.direct_sum(v2)
print(f"Direct sum of v1 and v2 = {v1_dsum_v2}")

Direct sum of v1 and v2 = {0, 1, 2, 3, 4, 5}


#### Computing Quotient

In [7]:
V1_qot_subv1 = v1.quotient_space(subv1)
print(f"v1 = {v1}, sub v1 = {subv1}")
print(f"Quotient space = {V1_qot_subv1}")


v1 = {0, 1, 2, 3}, sub v1 = {0, 2}
Quotient space = {0, 1, 3}


#### Computing Dimension of F1VS

In [8]:
print(f"v1 = {v1}, Dimension of v1 = {v1.dimn()}")

print(f"v2 = {v2}, Dimension of v2 = {v2.dimn()}")

print(f"v1_dsum_v2 = {v1_dsum_v2}, Dimension of v1_dsum_v2 = {v1_dsum_v2.dimn()}")

v1 = {0, 1, 2, 3}, Dimension of v1 = 3
v2 = {0, 4, 5}, Dimension of v2 = 2
v1_dsum_v2 = {0, 1, 2, 3, 4, 5}, Dimension of v1_dsum_v2 = 5


### F1 Linear Maps (Class of F1 linear maps)

#### Creating an F1 linear map

In [9]:
# Define a valid mapping: {0 → 0, 1 → 0, 2 → 4, 3 → 5}
mapping = {0: 0, 1: 0, 2: 4, 3: 5}
f = F1Map(v1, v2, mapping)
print(f)

F1Map({0: 0, 1: 0, 2: 4, 3: 5})


In [10]:
print(type(f))

<class 'f1.F1Map'>


### Kernel of F1 Linear Maps

In [11]:
ker = f.kernel()
print("Kernel of f:", ker)

Kernel of f: {0, 1}


##### Finding types and dimension of kernel

In [12]:
print("type of kernel of f: ",type(ker))
print("Dimension of kernel of f: ", ker.dimn())

type of kernel of f:  <class 'f1.F1VS'>
Dimension of kernel of f:  1


### Computing Image of F1Maps

In [13]:
f.image()

{0, 4, 5}

In [14]:
type(f.image())

f1.F1VS

#### Verifying Rank-Nullity for F1 Vector Spaces
Let f : v1 to v2 be an F1Map, R(f) is dimension of image of f and N(f) is dimension of kernel of f then,
R(f) + N(f) = dim(v1) .

In [15]:
print(f.image().dimn() + ker.dimn() == v1.dimn())


True


#### Verifying Isomorphism

In [16]:
v3 = F1VS([3,4,5])
v4 = F1VS([6,7,8])
# Define a valid mapping: {0 → 0, 3 → 6, 4 → 7, 5 → 8}
f_mapping = {0:0, 3:6, 4:7, 5:8}
f1 = F1Map(v3, v4,f_mapping)
print("Is f an isomorphism?", f1.is_isomorphic())  # Expected: True

# Define a non-isomorphic mapping (not surjective): {0 → 0, 1 → 4, 2 → 0, 3 → 5}
f2_mapping = {0: 0, 3: 0, 4: 6, 5: 7}

f2 = F1Map(v3, v4, f2_mapping)
print("Is fn an isomorphism?", f2.is_isomorphic())  # Expected: False


Is f an isomorphism? True
Is fn an isomorphism? False


### Verifying 1st Isomorphism theorem

In [17]:
g = F1Map(v1.quotient_space(f.kernel()), f.image(), mapping)
g.is_isomorphic()

True

In [18]:
h = F1Map(v3.quotient_space(f1.kernel()), f1.image(), f_mapping)
h.is_isomorphic()

True

#### Computing CoKernel

In [19]:
coker = v2.quotient_space(f.image())
coker

{0}

#### Representing F1Map as Matrix

In [20]:
V1 = F1VS({1, 2, 3})
V2 = F1VS({4, 5})

# Define a mapping: {0 → 0, 1 → 4, 2 → 5, 3 → 6}
mapping = {0: 0, 1: 0, 2: 4, 3: 5}

f = F1Map(v1, v2, mapping)

# Get the NumPy matrix
matrix = f.to_matrix()
print(matrix)

[[0 1 0]
 [0 0 1]]


In [21]:
type(matrix)

numpy.ndarray

#### Jordan Normal Form of F1Map

In [22]:
mapping_nfl = {0:0, 1:0, 2:1, 3:2}
nlf = F1Map(v1,v1, mapping_nfl)
nlf.to_matrix()

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

#### F1 Endomorphisms

In [29]:
V1 = F1VS({1, 2, 3})

# Define an endomorphism: {0 → 0, 1 → 0, 2 → 1, 3 → 2}
mapping_nfl = {0: 0, 1: 0, 2: 1, 3: 2}

F1endo = F1Map(V1, V1, mapping_nfl)  # Endomorphism of index 1

# Find endomorphism of index 2
F1endo2 = F1endo.iter_endomorphism(2)

# Find endomorphism of index 3
F1endo3 = F1endo.iter_endomorphism(3)

F1endo4 = F1endo.iter_endomorphism(4)

print("F1endo2:", F1endo2.mapping)
print("F1endo3:", F1endo3.mapping) 
print("F1endo4:", F1endo4.mapping)


F1endo2: {0: 0, 1: 0, 2: 1}
F1endo3: {0: 0, 1: 0}
F1endo4: {0: 0}
